services:
  auth:
    container_name: auth
    env_file:
      - .env
    environment:
      PG_DB_HOST: postgres
      NATS_URL: nats://nats:4222
    build:
      context: .
      args:
        - SERVICE_NAME=auth
    image: docker.freefrog.tech/min/auth:dev
    restart: always
    ports:
      - 3001:3000
    depends_on:
      nats:
        condition: service_started
      postgres:
        condition: service_healthy

  gate:
    container_name: gate
    env_file:
      - .env
    environment:
      NATS_URL: nats://nats:4222
    build:
      context: .
      args:
        - SERVICE_NAME=gate
    image: docker.freefrog.tech/min/gate:dev
    restart: always
    depends_on:
      nats:
        condition: service_started
    ports:
      - 3002:3000

  user:
    container_name: user
    env_file:
      - .env
    environment:
      PG_DB_HOST: postgres
      NATS_URL: nats://nats:4222
    build:
      context: .
      args:
        - SERVICE_NAME=user
    image: docker.freefrog.tech/min/user:dev
    restart: always
    ports:
      - 3003:3000
    depends_on:
      nats:
        condition: service_started
      postgres:
        condition: service_healthy

  message:
    container_name: message
    env_file:
      - .env
    environment:
      PG_DB_HOST: postgres
      NATS_URL: nats://nats:4222
    build:
      context: .
      args:
        - SERVICE_NAME=message
    image: docker.freefrog.tech/min/message:dev
    restart: always
    ports:
      - 3004:3000
    depends_on:
      nats:
        condition: service_started
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${PG_DB_NAME:-postgres}
      POSTGRES_USER: ${PG_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD:-postgres}
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "${PG_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.10.10
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

volumes:
  postgres_data:
  pgadmin_data:
