version: "3.9"
services:
  auth:
    container_name: auth
    env_file:
      - .env
    environment:
      PG_DB_HOST: ${PG_DB_HOST}
      PG_DB_PORT: ${PG_DB_PORT}
      PG_DB_NAME: ${PG_DB_NAME}
      PG_DB_USER: ${PG_DB_USER}
      PG_DB_PASSWORD: ${PG_DB_PASSWORD}
    build:
      context: .
      args:
        - SERVICE_NAME=auth
    image: docker.freefrog.tech/min/auth:dev
    restart: always
    ports:
      - 3001:3000
    depends_on:
      - nats
      - postgres

  gate:
    container_name: gate
    env_file:
      - .env
    environment:
      GATE_APP_HOST: ${GATE_APP_HOST}
      GATE_APP_PORT: ${GATE_APP_PORT}
      NODE_ENV: ${NODE_ENV}
      RMQ_URL: ${RMQ_URL}
    build:
      context: .
      args:
        - SERVICE_NAME=gate
    image: docker.freefrog.tech/min/gate:dev
    restart: always
    depends_on:
      - nats
    ports:
      - 3002:3000

  user:
    container_name: user
    env_file:
      - .env
    environment:
      PG_DB_HOST: ${PG_DB_HOST}
      PG_DB_PORT: ${PG_DB_PORT}
      PG_DB_NAME: ${PG_DB_NAME}
      PG_DB_USER: ${PG_DB_USER}
      PG_DB_PASSWORD: ${PG_DB_PASSWORD}
    build:
      context: .
      args:
        - SERVICE_NAME=user
    image: docker.freefrog.tech/min/user:dev
    restart: always
    ports:
      - 3003:3000
    depends_on:
      - nats
      - postgres

  message:
    container_name: message
    env_file:
      - .env
    environment:
      PG_DB_HOST: ${PG_DB_HOST}
      PG_DB_PORT: ${PG_DB_PORT}
      PG_DB_NAME: ${PG_DB_NAME}
      PG_DB_USER: ${PG_DB_USER}
      PG_DB_PASSWORD: ${PG_DB_PASSWORD}
    build:
      context: .
      args:
        - SERVICE_NAME=message
    image: docker.freefrog.tech/min/message:dev
    restart: always
    ports:
      - 3004:3000
    depends_on:
      - nats
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - example.env
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "${PG_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats:2.10.10
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

volumes:
  postgres_data:
  pgadmin_data:
